### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by mattjennings** [KyoheiG3/SpringIndicator#13]
Any plans on updating for Swift 3.0 compatibility?

**Comment by tosbaha** [comment]
I sent a PR #14 . In the mean time, check my [fork](https://github.com/tosbaha/SpringIndicator) please. I also fixed the tiny bug.

**Comment by mattjennings** [comment]
Awesome, thanks!!

**Comment by KyoheiG3** [comment]
Supported in https://github.com/KyoheiG3/SpringIndicator/pull/15 with the latest Xcode.
