### ISSUE TITLE
xcode 8.3 Warnings

### ISSUE THREAD

**Issue by ergunkocak** [KyoheiG3/SpringIndicator#21]
Hello,

xcode 8.3 is displaying 11 new warnings :

- SpringIndicator.swift:28:30: Method 'initialize()' defines Objective-C class method 'initialize', which is not guaranteed to be invoked by Swift and will be disallowed in future versions

- SpringIndicator.swift:42:40: 'M_PI' is deprecated: Please use 'Double.pi' or '.pi' to get the value of correct type and avoid casting.

- SpringIndicator.swift:42:47: 'M_PI_2' is deprecated: Please use 'Double.pi / 2' or '.pi / 2' to get the value of correct type and avoid casting.

- SpringIndicator.swift:232:29: 'M_PI_2' is deprecated: Please use 'Double.pi / 2' or '.pi / 2' to get the value of correct type and avoid casting.

- SpringIndicator.swift:233:27: 'M_PI_2' is deprecated: Please use 'Double.pi / 2' or '.pi / 2' to get the value of correct type and avoid casting.

- SpringIndicator.swift:348:28: 'M_PI' is deprecated: Please use 'Double.pi' or '.pi' to get the value of correct type and avoid casting.

- SpringIndicator.swift:348:35: 'M_PI_4' is deprecated: Please use 'Double.pi / 4' or '.pi / 4' to get the value of correct type and avoid casting.

- SpringIndicator.swift:349:24: 'M_PI' is deprecated: Please use 'Double.pi' or '.pi' to get the value of correct type and avoid casting.

- SpringIndicator.swift:349:31: 'M_PI_4' is deprecated: Please use 'Double.pi / 4' or '.pi / 4' to get the value of correct type and avoid casting.

- SpringIndicator.swift:499:85: 'M_PI' is deprecated: Please use 'Double.pi' or '.pi' to get the value of correct type and avoid casting.

- SpringIndicator.swift:499:92: 'M_PI_4' is deprecated: Please use 'Double.pi / 4' or '.pi / 4' to get the value of correct type and avoid casting.

**Comment by pranjalsatija** [comment]
@ergunkocak You can fix all the `M_PI` / `M_PI_2` / `M_PI_4` errors by replacing `M_PI` with `Double.pi`, `M_PI_2` with `Double.pi / 2`, and `M_PI_4` with `Double.pi / 4`. I'm having a lot more trouble with fixing the `initialize()` warning though. `initialize()` is called by the Objective C runtime once per class, before that class is sent any messages whatsoever. I tried 2, both of which were from [this StackOverflow answer](http://stackoverflow.com/questions/42824541/swift-3-1-deprecates-initialize-how-can-i-achieve-the-same-thing), but I still haven't been able to resolve this issue.

@KyoheiG3 Do you have any input?

**Comment by pranjalsatija** [comment]
@ergunkocak @KyoheiG3 Quick update. When changing the `M_PI` constants to `Double.pi` values, I made some mistakes with parentheses. This took **forever** to track down, so I recommend that you wrap statements like `Double.pi / 2` in parentheses: `(Double.pi / 2)` to avoid bugs.

**Comment by burhanaksendir** [comment]
@KyoheiG3 Do you have any input?

**Comment by burhanaksendir** [comment]
@ergunkocak I'm having the same problem. Did you solve it?

**Comment by KyoheiG3** [comment]
@pranjalsatija @burhanaksendir Hi.
I solved these warnings in [1.5.0](https://github.com/KyoheiG3/SpringIndicator/releases/tag/1.5.0)
Thank you, guys.

**Comment by burhanaksendir** [comment]
@KyoheiG3 Thanks
