### ISSUE TITLE
Crashed: SpringIndicator.Timer.Thread

### ISSUE THREAD

**Issue by shadiabusamra** [KyoheiG3/SpringIndicator#22]
Stack trace 

> Crashed: SpringIndicator.Timer.Thread
0  WebCore                        0x1891c9950 _WebTryThreadLock(bool) + 192
1  WebCore                        0x1891c9fc4 WebThreadLock + 108
2  UIKit                          0x18a90e79c -[UIWebTiledView layoutSubviews] + 52
3  UIKit                          0x18a90d484 -[UIWebDocumentView layoutSubviews] + 168
4  UIKit                          0x18a8bbf50 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1256
5  QuartzCore                     0x184ec3670 -[CALayer layoutSublayers] + 184
6  QuartzCore                     0x184ec7748 CA::Layer::layout_if_needed(CA::Transaction*) + 332
7  QuartzCore                     0x184e37954 CA::Context::commit_transaction(CA::Transaction*) + 336
8  QuartzCore                     0x184e5dd44 CA::Transaction::commit() + 540
9  QuartzCore                     0x184e5eb90 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 92
10 CoreFoundation                 0x180d38ad0 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
11 CoreFoundation                 0x180d36488 __CFRunLoopDoObservers + 412
12 CoreFoundation                 0x180d36a44 __CFRunLoopRun + 1292
13 CoreFoundation                 0x180c57558 CFRunLoopRunSpecific + 436
14 Foundation                     0x18167acc4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
15 Foundation                     0x1816ccc7c -[NSRunLoop(NSRunLoop) run] + 88
16 TebBaby                        0x10189773c closure #1 in closure #1 in variable initialization expression of static SpringIndicator.timerQueue (SpringIndicator.swift:34)
17 TebBaby                        0x101722678 thunk for @callee_owned () -> () (PhotoGallaryCameraViewController.swift)
18 libdispatch.dylib              0x18071546c _dispatch_call_block_and_release + 24
19 libdispatch.dylib              0x18071542c _dispatch_client_callout + 16
20 libdispatch.dylib              0x18071d76c _dispatch_continuation_pop$VARIANT$mp + 428
21 libdispatch.dylib              0x18071c06c _dispatch_async_redirect_invoke$VARIANT$mp + 604
22 libdispatch.dylib              0x1807224c4 _dispatch_root_queue_drain + 596
23 libdispatch.dylib              0x18072220c _dispatch_worker_thread3 + 120
24 libsystem_pthread.dylib        0x1809bc11c _pthread_wqthread + 1268
25 libsystem_pthread.dylib        0x1809bbc1c start_wqthread + 4

**Comment by KyoheiG3** [comment]
Fixed in [2.0.0](https://github.com/KyoheiG3/SpringIndicator/releases/tag/2.0.0)

**Comment by shadiabusamra** [comment]
Thanks.
