### ISSUE TITLE
Indicator does not display using CAPSPageMenu

### ISSUE THREAD

**Issue by ed-mejia** [KyoheiG3/SpringIndicator#3]
Hi I'm trying to use this great controller in conjunction with this lib https://github.com/uacaps/PageMenu (Instagram segmented example) as a refresher for a tableview, everything seams to work ok, but the indicator is not being displayed, If I add the controller to a simple tableview it works ok.

It seems the controller is not taken the right top position of the table?, how can I fix this issue?

Thanks for the help.
![screen shot 2015-06-05 at 5 23 54 pm](https://cloud.githubusercontent.com/assets/7431094/8001311/ea2cb5bc-0ba7-11e5-9231-88b4bdc5d1ad.png)

**Comment by ed-mejia** [comment]
If I add a standard UIRefreshControl it is displayed properly

**Comment by ed-mejia** [comment]
You just need to add
refreshIndicator.layoutIfNeeded()

After you add the controller to the tableView

**Comment by KyoheiG3** [comment]
Where it must be added? Thanks.

**Comment by ed-mejia** [comment]
Hi, just after you add it to the tableView:

var refreshIndicator = SpringIndicator.Refresher()
refreshIndicator.addTarget(self, action: "onRefresh", forControlEvents: .ValueChanged)
tableView.addSubview(refreshIndicator)
refreshIndicator.layoutIfNeeded()

**Comment by KyoheiG3** [comment]
It was no problem and I tried in [Demo1](https://github.com/KyoheiG3/PageMenu/tree/master/Demos/Demo%201/PageMenuDemoStoryboard).

However, I try to fix.
Because might `layoutIfNeeded` is not called after the `addSubview`.

**Comment by KyoheiG3** [comment]
Fixed in [1.1.4](https://github.com/KyoheiG3/SpringIndicator/tree/1.1.4).
