### ISSUE TITLE
xcode10 & swift 4.2 not compiling

### ISSUE THREAD

**Issue by ergunkocak** [KyoheiG3/SpringIndicator#32]
Would you please merge https://github.com/KyoheiG3/SpringIndicator/pull/31

**Comment by KyoheiG3** [comment]
Hi @ergunkocak 
It was merged.
Thanks.

**Comment by ergunkocak** [comment]
Thanks very much for fast response. will we have a new version for cocoapods? Or shall we use master branch instead of version 3.0.0?

**Comment by KyoheiG3** [comment]
[4.0.0](https://github.com/KyoheiG3/SpringIndicator/releases) released.
Thanks again.
