### ISSUE TITLE
Swift package doesn't work

### ISSUE THREAD

**Issue by albcc** [KyoheiG3/SpringIndicator#37]
I just tried to add SpringIndicator swift package but
![Schermata 2020-09-21 alle 18 46 22](https://user-images.githubusercontent.com/5058030/93796436-24ddb100-fc3b-11ea-8267-ec8ff6db3798.png)

Also tried to set an exact version to 5.1.0 but still no luck

![Schermata 2020-09-21 alle 18 43 19](https://user-images.githubusercontent.com/5058030/93796429-2313ed80-fc3b-11ea-9340-b39f0be48d71.png)

**Comment by KyoheiG3** [comment]
5.1.0 tag is added now.
please try again.

**Comment by albcc** [comment]
@KyoheiG3 done and it's working.
