### ISSUE TITLE
SpringIndicator.lineColorを設定しても色が変わらない

### ISSUE THREAD

**Issue by smztko** [KyoheiG3/SpringIndicator#7]
## 内容

`SpringIndicator.lineColor`をコードから設定しても色が変わりません。

## 状況

- StoryBoardでViewを作成し、その上に`SpringIndicator`を配置
- コードからViewをインスタンス化し、`awakeFromNib()`で`lineColor`を設定
- 色の変更が反映されていない
- StoryBoardから色を変更できることは確認済み

## 要望

コードから`lineColor`を設定したいです。

**Comment by KyoheiG3** [comment]
コードからViewのインスタンスを作成するとはどういう状況でしょう、nibからインスタンスを取得でしょうか？

https://github.com/KyoheiG3/SpringIndicator/blob/master/SpringIndicatorExample/SpringIndicatorExample/ViewController.swift#L26
`lineColor`については、この辺りを参考にしてもらえると良いかと思います。

**Comment by smztko** [comment]
お返事ありがとうございました。
また、返答が大変遅くなり、申し訳ありません。

サンプルコードのように修正したところ、確認できました。
